// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset/internalclientset/typed/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNetoperatorV1alpha1 struct {
	*testing.Fake
}

func (c *FakeNetoperatorV1alpha1) AviLoadBalancerConfigs() v1alpha1.AviLoadBalancerConfigInterface {
	return &FakeAviLoadBalancerConfigs{c}
}

func (c *FakeNetoperatorV1alpha1) FoundationLoadBalancerConfigs(namespace string) v1alpha1.FoundationLoadBalancerConfigInterface {
	return &FakeFoundationLoadBalancerConfigs{c, namespace}
}

func (c *FakeNetoperatorV1alpha1) HAProxyLoadBalancerConfigs() v1alpha1.HAProxyLoadBalancerConfigInterface {
	return &FakeHAProxyLoadBalancerConfigs{c}
}

func (c *FakeNetoperatorV1alpha1) IPAddressAllocations(namespace string) v1alpha1.IPAddressAllocationInterface {
	return &FakeIPAddressAllocations{c, namespace}
}

func (c *FakeNetoperatorV1alpha1) IPPools() v1alpha1.IPPoolInterface {
	return &FakeIPPools{c}
}

func (c *FakeNetoperatorV1alpha1) LoadBalancerConfigs() v1alpha1.LoadBalancerConfigInterface {
	return &FakeLoadBalancerConfigs{c}
}

func (c *FakeNetoperatorV1alpha1) NamespaceNetworkConfigurations() v1alpha1.NamespaceNetworkConfigurationInterface {
	return &FakeNamespaceNetworkConfigurations{c}
}

func (c *FakeNetoperatorV1alpha1) Networks(namespace string) v1alpha1.NetworkInterface {
	return &FakeNetworks{c, namespace}
}

func (c *FakeNetoperatorV1alpha1) NetworkInterfaces(namespace string) v1alpha1.NetworkInterfaceInterface {
	return &FakeNetworkInterfaces{c, namespace}
}

func (c *FakeNetoperatorV1alpha1) NetworkSettingses(namespace string) v1alpha1.NetworkSettingsInterface {
	return &FakeNetworkSettingses{c, namespace}
}

func (c *FakeNetoperatorV1alpha1) VMXNET3NetworkInterfaces(namespace string) v1alpha1.VMXNET3NetworkInterfaceInterface {
	return &FakeVMXNET3NetworkInterfaces{c, namespace}
}

func (c *FakeNetoperatorV1alpha1) VSphereDistributedNetworks() v1alpha1.VSphereDistributedNetworkInterface {
	return &FakeVSphereDistributedNetworks{c}
}

func (c *FakeNetoperatorV1alpha1) WorkloadNetworkConfigurations() v1alpha1.WorkloadNetworkConfigurationInterface {
	return &FakeWorkloadNetworkConfigurations{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNetoperatorV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
