// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHAProxyLoadBalancerConfigs implements HAProxyLoadBalancerConfigInterface
type FakeHAProxyLoadBalancerConfigs struct {
	Fake *FakeNetoperatorV1alpha1
}

var haproxyloadbalancerconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("haproxyloadbalancerconfigs")

var haproxyloadbalancerconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("HAProxyLoadBalancerConfig")

// Get takes name of the hAProxyLoadBalancerConfig, and returns the corresponding hAProxyLoadBalancerConfig object, and an error if there is any.
func (c *FakeHAProxyLoadBalancerConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HAProxyLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(haproxyloadbalancerconfigsResource, name), &v1alpha1.HAProxyLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HAProxyLoadBalancerConfig), err
}

// List takes label and field selectors, and returns the list of HAProxyLoadBalancerConfigs that match those selectors.
func (c *FakeHAProxyLoadBalancerConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HAProxyLoadBalancerConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(haproxyloadbalancerconfigsResource, haproxyloadbalancerconfigsKind, opts), &v1alpha1.HAProxyLoadBalancerConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HAProxyLoadBalancerConfigList{ListMeta: obj.(*v1alpha1.HAProxyLoadBalancerConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.HAProxyLoadBalancerConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hAProxyLoadBalancerConfigs.
func (c *FakeHAProxyLoadBalancerConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(haproxyloadbalancerconfigsResource, opts))
}

// Create takes the representation of a hAProxyLoadBalancerConfig and creates it.  Returns the server's representation of the hAProxyLoadBalancerConfig, and an error, if there is any.
func (c *FakeHAProxyLoadBalancerConfigs) Create(ctx context.Context, hAProxyLoadBalancerConfig *v1alpha1.HAProxyLoadBalancerConfig, opts v1.CreateOptions) (result *v1alpha1.HAProxyLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(haproxyloadbalancerconfigsResource, hAProxyLoadBalancerConfig), &v1alpha1.HAProxyLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HAProxyLoadBalancerConfig), err
}

// Update takes the representation of a hAProxyLoadBalancerConfig and updates it. Returns the server's representation of the hAProxyLoadBalancerConfig, and an error, if there is any.
func (c *FakeHAProxyLoadBalancerConfigs) Update(ctx context.Context, hAProxyLoadBalancerConfig *v1alpha1.HAProxyLoadBalancerConfig, opts v1.UpdateOptions) (result *v1alpha1.HAProxyLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(haproxyloadbalancerconfigsResource, hAProxyLoadBalancerConfig), &v1alpha1.HAProxyLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HAProxyLoadBalancerConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHAProxyLoadBalancerConfigs) UpdateStatus(ctx context.Context, hAProxyLoadBalancerConfig *v1alpha1.HAProxyLoadBalancerConfig, opts v1.UpdateOptions) (*v1alpha1.HAProxyLoadBalancerConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(haproxyloadbalancerconfigsResource, "status", hAProxyLoadBalancerConfig), &v1alpha1.HAProxyLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HAProxyLoadBalancerConfig), err
}

// Delete takes name of the hAProxyLoadBalancerConfig and deletes it. Returns an error if one occurs.
func (c *FakeHAProxyLoadBalancerConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(haproxyloadbalancerconfigsResource, name, opts), &v1alpha1.HAProxyLoadBalancerConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHAProxyLoadBalancerConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(haproxyloadbalancerconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HAProxyLoadBalancerConfigList{})
	return err
}

// Patch applies the patch and returns the patched hAProxyLoadBalancerConfig.
func (c *FakeHAProxyLoadBalancerConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HAProxyLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(haproxyloadbalancerconfigsResource, name, pt, data, subresources...), &v1alpha1.HAProxyLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HAProxyLoadBalancerConfig), err
}
