// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkloadNetworkConfigurations implements WorkloadNetworkConfigurationInterface
type FakeWorkloadNetworkConfigurations struct {
	Fake *FakeNetoperatorV1alpha1
}

var workloadnetworkconfigurationsResource = v1alpha1.SchemeGroupVersion.WithResource("workloadnetworkconfigurations")

var workloadnetworkconfigurationsKind = v1alpha1.SchemeGroupVersion.WithKind("WorkloadNetworkConfiguration")

// Get takes name of the workloadNetworkConfiguration, and returns the corresponding workloadNetworkConfiguration object, and an error if there is any.
func (c *FakeWorkloadNetworkConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(workloadnetworkconfigurationsResource, name), &v1alpha1.WorkloadNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadNetworkConfiguration), err
}

// List takes label and field selectors, and returns the list of WorkloadNetworkConfigurations that match those selectors.
func (c *FakeWorkloadNetworkConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkloadNetworkConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(workloadnetworkconfigurationsResource, workloadnetworkconfigurationsKind, opts), &v1alpha1.WorkloadNetworkConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkloadNetworkConfigurationList{ListMeta: obj.(*v1alpha1.WorkloadNetworkConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkloadNetworkConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workloadNetworkConfigurations.
func (c *FakeWorkloadNetworkConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(workloadnetworkconfigurationsResource, opts))
}

// Create takes the representation of a workloadNetworkConfiguration and creates it.  Returns the server's representation of the workloadNetworkConfiguration, and an error, if there is any.
func (c *FakeWorkloadNetworkConfigurations) Create(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.CreateOptions) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(workloadnetworkconfigurationsResource, workloadNetworkConfiguration), &v1alpha1.WorkloadNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadNetworkConfiguration), err
}

// Update takes the representation of a workloadNetworkConfiguration and updates it. Returns the server's representation of the workloadNetworkConfiguration, and an error, if there is any.
func (c *FakeWorkloadNetworkConfigurations) Update(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.UpdateOptions) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(workloadnetworkconfigurationsResource, workloadNetworkConfiguration), &v1alpha1.WorkloadNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadNetworkConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkloadNetworkConfigurations) UpdateStatus(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.UpdateOptions) (*v1alpha1.WorkloadNetworkConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(workloadnetworkconfigurationsResource, "status", workloadNetworkConfiguration), &v1alpha1.WorkloadNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadNetworkConfiguration), err
}

// Delete takes name of the workloadNetworkConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeWorkloadNetworkConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(workloadnetworkconfigurationsResource, name, opts), &v1alpha1.WorkloadNetworkConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkloadNetworkConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(workloadnetworkconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkloadNetworkConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched workloadNetworkConfiguration.
func (c *FakeWorkloadNetworkConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(workloadnetworkconfigurationsResource, name, pt, data, subresources...), &v1alpha1.WorkloadNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadNetworkConfiguration), err
}
