// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNamespaceNetworkConfigurations implements NamespaceNetworkConfigurationInterface
type FakeNamespaceNetworkConfigurations struct {
	Fake *FakeNetoperatorV1alpha1
}

var namespacenetworkconfigurationsResource = v1alpha1.SchemeGroupVersion.WithResource("namespacenetworkconfigurations")

var namespacenetworkconfigurationsKind = v1alpha1.SchemeGroupVersion.WithKind("NamespaceNetworkConfiguration")

// Get takes name of the namespaceNetworkConfiguration, and returns the corresponding namespaceNetworkConfiguration object, and an error if there is any.
func (c *FakeNamespaceNetworkConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NamespaceNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(namespacenetworkconfigurationsResource, name), &v1alpha1.NamespaceNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceNetworkConfiguration), err
}

// List takes label and field selectors, and returns the list of NamespaceNetworkConfigurations that match those selectors.
func (c *FakeNamespaceNetworkConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NamespaceNetworkConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(namespacenetworkconfigurationsResource, namespacenetworkconfigurationsKind, opts), &v1alpha1.NamespaceNetworkConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NamespaceNetworkConfigurationList{ListMeta: obj.(*v1alpha1.NamespaceNetworkConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.NamespaceNetworkConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested namespaceNetworkConfigurations.
func (c *FakeNamespaceNetworkConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(namespacenetworkconfigurationsResource, opts))
}

// Create takes the representation of a namespaceNetworkConfiguration and creates it.  Returns the server's representation of the namespaceNetworkConfiguration, and an error, if there is any.
func (c *FakeNamespaceNetworkConfigurations) Create(ctx context.Context, namespaceNetworkConfiguration *v1alpha1.NamespaceNetworkConfiguration, opts v1.CreateOptions) (result *v1alpha1.NamespaceNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(namespacenetworkconfigurationsResource, namespaceNetworkConfiguration), &v1alpha1.NamespaceNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceNetworkConfiguration), err
}

// Update takes the representation of a namespaceNetworkConfiguration and updates it. Returns the server's representation of the namespaceNetworkConfiguration, and an error, if there is any.
func (c *FakeNamespaceNetworkConfigurations) Update(ctx context.Context, namespaceNetworkConfiguration *v1alpha1.NamespaceNetworkConfiguration, opts v1.UpdateOptions) (result *v1alpha1.NamespaceNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(namespacenetworkconfigurationsResource, namespaceNetworkConfiguration), &v1alpha1.NamespaceNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceNetworkConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNamespaceNetworkConfigurations) UpdateStatus(ctx context.Context, namespaceNetworkConfiguration *v1alpha1.NamespaceNetworkConfiguration, opts v1.UpdateOptions) (*v1alpha1.NamespaceNetworkConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(namespacenetworkconfigurationsResource, "status", namespaceNetworkConfiguration), &v1alpha1.NamespaceNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceNetworkConfiguration), err
}

// Delete takes name of the namespaceNetworkConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeNamespaceNetworkConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(namespacenetworkconfigurationsResource, name, opts), &v1alpha1.NamespaceNetworkConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNamespaceNetworkConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(namespacenetworkconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NamespaceNetworkConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched namespaceNetworkConfiguration.
func (c *FakeNamespaceNetworkConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NamespaceNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(namespacenetworkconfigurationsResource, name, pt, data, subresources...), &v1alpha1.NamespaceNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceNetworkConfiguration), err
}
