// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLoadBalancerConfigs implements LoadBalancerConfigInterface
type FakeLoadBalancerConfigs struct {
	Fake *FakeNetoperatorV1alpha1
}

var loadbalancerconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("loadbalancerconfigs")

var loadbalancerconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("LoadBalancerConfig")

// Get takes name of the loadBalancerConfig, and returns the corresponding loadBalancerConfig object, and an error if there is any.
func (c *FakeLoadBalancerConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(loadbalancerconfigsResource, name), &v1alpha1.LoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LoadBalancerConfig), err
}

// List takes label and field selectors, and returns the list of LoadBalancerConfigs that match those selectors.
func (c *FakeLoadBalancerConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LoadBalancerConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(loadbalancerconfigsResource, loadbalancerconfigsKind, opts), &v1alpha1.LoadBalancerConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LoadBalancerConfigList{ListMeta: obj.(*v1alpha1.LoadBalancerConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.LoadBalancerConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested loadBalancerConfigs.
func (c *FakeLoadBalancerConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(loadbalancerconfigsResource, opts))
}

// Create takes the representation of a loadBalancerConfig and creates it.  Returns the server's representation of the loadBalancerConfig, and an error, if there is any.
func (c *FakeLoadBalancerConfigs) Create(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.CreateOptions) (result *v1alpha1.LoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(loadbalancerconfigsResource, loadBalancerConfig), &v1alpha1.LoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LoadBalancerConfig), err
}

// Update takes the representation of a loadBalancerConfig and updates it. Returns the server's representation of the loadBalancerConfig, and an error, if there is any.
func (c *FakeLoadBalancerConfigs) Update(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.UpdateOptions) (result *v1alpha1.LoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(loadbalancerconfigsResource, loadBalancerConfig), &v1alpha1.LoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LoadBalancerConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLoadBalancerConfigs) UpdateStatus(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.UpdateOptions) (*v1alpha1.LoadBalancerConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(loadbalancerconfigsResource, "status", loadBalancerConfig), &v1alpha1.LoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LoadBalancerConfig), err
}

// Delete takes name of the loadBalancerConfig and deletes it. Returns an error if one occurs.
func (c *FakeLoadBalancerConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(loadbalancerconfigsResource, name, opts), &v1alpha1.LoadBalancerConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLoadBalancerConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(loadbalancerconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LoadBalancerConfigList{})
	return err
}

// Patch applies the patch and returns the patched loadBalancerConfig.
func (c *FakeLoadBalancerConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(loadbalancerconfigsResource, name, pt, data, subresources...), &v1alpha1.LoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LoadBalancerConfig), err
}
