// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFoundationLoadBalancerConfigs implements FoundationLoadBalancerConfigInterface
type FakeFoundationLoadBalancerConfigs struct {
	Fake *FakeNetoperatorV1alpha1
	ns   string
}

var foundationloadbalancerconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("foundationloadbalancerconfigs")

var foundationloadbalancerconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("FoundationLoadBalancerConfig")

// Get takes name of the foundationLoadBalancerConfig, and returns the corresponding foundationLoadBalancerConfig object, and an error if there is any.
func (c *FakeFoundationLoadBalancerConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FoundationLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(foundationloadbalancerconfigsResource, c.ns, name), &v1alpha1.FoundationLoadBalancerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FoundationLoadBalancerConfig), err
}

// List takes label and field selectors, and returns the list of FoundationLoadBalancerConfigs that match those selectors.
func (c *FakeFoundationLoadBalancerConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FoundationLoadBalancerConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(foundationloadbalancerconfigsResource, foundationloadbalancerconfigsKind, c.ns, opts), &v1alpha1.FoundationLoadBalancerConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FoundationLoadBalancerConfigList{ListMeta: obj.(*v1alpha1.FoundationLoadBalancerConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.FoundationLoadBalancerConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested foundationLoadBalancerConfigs.
func (c *FakeFoundationLoadBalancerConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(foundationloadbalancerconfigsResource, c.ns, opts))

}

// Create takes the representation of a foundationLoadBalancerConfig and creates it.  Returns the server's representation of the foundationLoadBalancerConfig, and an error, if there is any.
func (c *FakeFoundationLoadBalancerConfigs) Create(ctx context.Context, foundationLoadBalancerConfig *v1alpha1.FoundationLoadBalancerConfig, opts v1.CreateOptions) (result *v1alpha1.FoundationLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(foundationloadbalancerconfigsResource, c.ns, foundationLoadBalancerConfig), &v1alpha1.FoundationLoadBalancerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FoundationLoadBalancerConfig), err
}

// Update takes the representation of a foundationLoadBalancerConfig and updates it. Returns the server's representation of the foundationLoadBalancerConfig, and an error, if there is any.
func (c *FakeFoundationLoadBalancerConfigs) Update(ctx context.Context, foundationLoadBalancerConfig *v1alpha1.FoundationLoadBalancerConfig, opts v1.UpdateOptions) (result *v1alpha1.FoundationLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(foundationloadbalancerconfigsResource, c.ns, foundationLoadBalancerConfig), &v1alpha1.FoundationLoadBalancerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FoundationLoadBalancerConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFoundationLoadBalancerConfigs) UpdateStatus(ctx context.Context, foundationLoadBalancerConfig *v1alpha1.FoundationLoadBalancerConfig, opts v1.UpdateOptions) (*v1alpha1.FoundationLoadBalancerConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(foundationloadbalancerconfigsResource, "status", c.ns, foundationLoadBalancerConfig), &v1alpha1.FoundationLoadBalancerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FoundationLoadBalancerConfig), err
}

// Delete takes name of the foundationLoadBalancerConfig and deletes it. Returns an error if one occurs.
func (c *FakeFoundationLoadBalancerConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(foundationloadbalancerconfigsResource, c.ns, name, opts), &v1alpha1.FoundationLoadBalancerConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFoundationLoadBalancerConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(foundationloadbalancerconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FoundationLoadBalancerConfigList{})
	return err
}

// Patch applies the patch and returns the patched foundationLoadBalancerConfig.
func (c *FakeFoundationLoadBalancerConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FoundationLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(foundationloadbalancerconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FoundationLoadBalancerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FoundationLoadBalancerConfig), err
}
