// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVSphereDistributedNetworks implements VSphereDistributedNetworkInterface
type FakeVSphereDistributedNetworks struct {
	Fake *FakeNetoperatorV1alpha1
}

var vspheredistributednetworksResource = v1alpha1.SchemeGroupVersion.WithResource("vspheredistributednetworks")

var vspheredistributednetworksKind = v1alpha1.SchemeGroupVersion.WithKind("VSphereDistributedNetwork")

// Get takes name of the vSphereDistributedNetwork, and returns the corresponding vSphereDistributedNetwork object, and an error if there is any.
func (c *FakeVSphereDistributedNetworks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(vspheredistributednetworksResource, name), &v1alpha1.VSphereDistributedNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSphereDistributedNetwork), err
}

// List takes label and field selectors, and returns the list of VSphereDistributedNetworks that match those selectors.
func (c *FakeVSphereDistributedNetworks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VSphereDistributedNetworkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(vspheredistributednetworksResource, vspheredistributednetworksKind, opts), &v1alpha1.VSphereDistributedNetworkList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VSphereDistributedNetworkList{ListMeta: obj.(*v1alpha1.VSphereDistributedNetworkList).ListMeta}
	for _, item := range obj.(*v1alpha1.VSphereDistributedNetworkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vSphereDistributedNetworks.
func (c *FakeVSphereDistributedNetworks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(vspheredistributednetworksResource, opts))
}

// Create takes the representation of a vSphereDistributedNetwork and creates it.  Returns the server's representation of the vSphereDistributedNetwork, and an error, if there is any.
func (c *FakeVSphereDistributedNetworks) Create(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.CreateOptions) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(vspheredistributednetworksResource, vSphereDistributedNetwork), &v1alpha1.VSphereDistributedNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSphereDistributedNetwork), err
}

// Update takes the representation of a vSphereDistributedNetwork and updates it. Returns the server's representation of the vSphereDistributedNetwork, and an error, if there is any.
func (c *FakeVSphereDistributedNetworks) Update(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.UpdateOptions) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(vspheredistributednetworksResource, vSphereDistributedNetwork), &v1alpha1.VSphereDistributedNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSphereDistributedNetwork), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVSphereDistributedNetworks) UpdateStatus(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.UpdateOptions) (*v1alpha1.VSphereDistributedNetwork, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(vspheredistributednetworksResource, "status", vSphereDistributedNetwork), &v1alpha1.VSphereDistributedNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSphereDistributedNetwork), err
}

// Delete takes name of the vSphereDistributedNetwork and deletes it. Returns an error if one occurs.
func (c *FakeVSphereDistributedNetworks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(vspheredistributednetworksResource, name, opts), &v1alpha1.VSphereDistributedNetwork{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVSphereDistributedNetworks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(vspheredistributednetworksResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VSphereDistributedNetworkList{})
	return err
}

// Patch applies the patch and returns the patched vSphereDistributedNetwork.
func (c *FakeVSphereDistributedNetworks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(vspheredistributednetworksResource, name, pt, data, subresources...), &v1alpha1.VSphereDistributedNetwork{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VSphereDistributedNetwork), err
}
