// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAviLoadBalancerConfigs implements AviLoadBalancerConfigInterface
type FakeAviLoadBalancerConfigs struct {
	Fake *FakeNetoperatorV1alpha1
}

var aviloadbalancerconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("aviloadbalancerconfigs")

var aviloadbalancerconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("AviLoadBalancerConfig")

// Get takes name of the aviLoadBalancerConfig, and returns the corresponding aviLoadBalancerConfig object, and an error if there is any.
func (c *FakeAviLoadBalancerConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(aviloadbalancerconfigsResource, name), &v1alpha1.AviLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AviLoadBalancerConfig), err
}

// List takes label and field selectors, and returns the list of AviLoadBalancerConfigs that match those selectors.
func (c *FakeAviLoadBalancerConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AviLoadBalancerConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(aviloadbalancerconfigsResource, aviloadbalancerconfigsKind, opts), &v1alpha1.AviLoadBalancerConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AviLoadBalancerConfigList{ListMeta: obj.(*v1alpha1.AviLoadBalancerConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.AviLoadBalancerConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aviLoadBalancerConfigs.
func (c *FakeAviLoadBalancerConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(aviloadbalancerconfigsResource, opts))
}

// Create takes the representation of a aviLoadBalancerConfig and creates it.  Returns the server's representation of the aviLoadBalancerConfig, and an error, if there is any.
func (c *FakeAviLoadBalancerConfigs) Create(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.CreateOptions) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(aviloadbalancerconfigsResource, aviLoadBalancerConfig), &v1alpha1.AviLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AviLoadBalancerConfig), err
}

// Update takes the representation of a aviLoadBalancerConfig and updates it. Returns the server's representation of the aviLoadBalancerConfig, and an error, if there is any.
func (c *FakeAviLoadBalancerConfigs) Update(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.UpdateOptions) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(aviloadbalancerconfigsResource, aviLoadBalancerConfig), &v1alpha1.AviLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AviLoadBalancerConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAviLoadBalancerConfigs) UpdateStatus(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.UpdateOptions) (*v1alpha1.AviLoadBalancerConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(aviloadbalancerconfigsResource, "status", aviLoadBalancerConfig), &v1alpha1.AviLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AviLoadBalancerConfig), err
}

// Delete takes name of the aviLoadBalancerConfig and deletes it. Returns an error if one occurs.
func (c *FakeAviLoadBalancerConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(aviloadbalancerconfigsResource, name, opts), &v1alpha1.AviLoadBalancerConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAviLoadBalancerConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(aviloadbalancerconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AviLoadBalancerConfigList{})
	return err
}

// Patch applies the patch and returns the patched aviLoadBalancerConfig.
func (c *FakeAviLoadBalancerConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(aviloadbalancerconfigsResource, name, pt, data, subresources...), &v1alpha1.AviLoadBalancerConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AviLoadBalancerConfig), err
}
