// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkSettingses implements NetworkSettingsInterface
type FakeNetworkSettingses struct {
	Fake *FakeNetoperatorV1alpha1
	ns   string
}

var networksettingsesResource = v1alpha1.SchemeGroupVersion.WithResource("networksettingses")

var networksettingsesKind = v1alpha1.SchemeGroupVersion.WithKind("NetworkSettings")

// Get takes name of the networkSettings, and returns the corresponding networkSettings object, and an error if there is any.
func (c *FakeNetworkSettingses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkSettings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networksettingsesResource, c.ns, name), &v1alpha1.NetworkSettings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSettings), err
}

// List takes label and field selectors, and returns the list of NetworkSettingses that match those selectors.
func (c *FakeNetworkSettingses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkSettingsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networksettingsesResource, networksettingsesKind, c.ns, opts), &v1alpha1.NetworkSettingsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkSettingsList{ListMeta: obj.(*v1alpha1.NetworkSettingsList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkSettingsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkSettingses.
func (c *FakeNetworkSettingses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networksettingsesResource, c.ns, opts))

}

// Create takes the representation of a networkSettings and creates it.  Returns the server's representation of the networkSettings, and an error, if there is any.
func (c *FakeNetworkSettingses) Create(ctx context.Context, networkSettings *v1alpha1.NetworkSettings, opts v1.CreateOptions) (result *v1alpha1.NetworkSettings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networksettingsesResource, c.ns, networkSettings), &v1alpha1.NetworkSettings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSettings), err
}

// Update takes the representation of a networkSettings and updates it. Returns the server's representation of the networkSettings, and an error, if there is any.
func (c *FakeNetworkSettingses) Update(ctx context.Context, networkSettings *v1alpha1.NetworkSettings, opts v1.UpdateOptions) (result *v1alpha1.NetworkSettings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networksettingsesResource, c.ns, networkSettings), &v1alpha1.NetworkSettings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSettings), err
}

// Delete takes name of the networkSettings and deletes it. Returns an error if one occurs.
func (c *FakeNetworkSettingses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(networksettingsesResource, c.ns, name, opts), &v1alpha1.NetworkSettings{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkSettingses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networksettingsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkSettingsList{})
	return err
}

// Patch applies the patch and returns the patched networkSettings.
func (c *FakeNetworkSettingses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkSettings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networksettingsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.NetworkSettings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSettings), err
}
