// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVMXNET3NetworkInterfaces implements VMXNET3NetworkInterfaceInterface
type FakeVMXNET3NetworkInterfaces struct {
	Fake *FakeNetoperatorV1alpha1
	ns   string
}

var vmxnet3networkinterfacesResource = v1alpha1.SchemeGroupVersion.WithResource("vmxnet3networkinterfaces")

var vmxnet3networkinterfacesKind = v1alpha1.SchemeGroupVersion.WithKind("VMXNET3NetworkInterface")

// Get takes name of the vMXNET3NetworkInterface, and returns the corresponding vMXNET3NetworkInterface object, and an error if there is any.
func (c *FakeVMXNET3NetworkInterfaces) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vmxnet3networkinterfacesResource, c.ns, name), &v1alpha1.VMXNET3NetworkInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMXNET3NetworkInterface), err
}

// List takes label and field selectors, and returns the list of VMXNET3NetworkInterfaces that match those selectors.
func (c *FakeVMXNET3NetworkInterfaces) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VMXNET3NetworkInterfaceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vmxnet3networkinterfacesResource, vmxnet3networkinterfacesKind, c.ns, opts), &v1alpha1.VMXNET3NetworkInterfaceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VMXNET3NetworkInterfaceList{ListMeta: obj.(*v1alpha1.VMXNET3NetworkInterfaceList).ListMeta}
	for _, item := range obj.(*v1alpha1.VMXNET3NetworkInterfaceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vMXNET3NetworkInterfaces.
func (c *FakeVMXNET3NetworkInterfaces) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vmxnet3networkinterfacesResource, c.ns, opts))

}

// Create takes the representation of a vMXNET3NetworkInterface and creates it.  Returns the server's representation of the vMXNET3NetworkInterface, and an error, if there is any.
func (c *FakeVMXNET3NetworkInterfaces) Create(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.CreateOptions) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vmxnet3networkinterfacesResource, c.ns, vMXNET3NetworkInterface), &v1alpha1.VMXNET3NetworkInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMXNET3NetworkInterface), err
}

// Update takes the representation of a vMXNET3NetworkInterface and updates it. Returns the server's representation of the vMXNET3NetworkInterface, and an error, if there is any.
func (c *FakeVMXNET3NetworkInterfaces) Update(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.UpdateOptions) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vmxnet3networkinterfacesResource, c.ns, vMXNET3NetworkInterface), &v1alpha1.VMXNET3NetworkInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMXNET3NetworkInterface), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVMXNET3NetworkInterfaces) UpdateStatus(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.UpdateOptions) (*v1alpha1.VMXNET3NetworkInterface, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vmxnet3networkinterfacesResource, "status", c.ns, vMXNET3NetworkInterface), &v1alpha1.VMXNET3NetworkInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMXNET3NetworkInterface), err
}

// Delete takes name of the vMXNET3NetworkInterface and deletes it. Returns an error if one occurs.
func (c *FakeVMXNET3NetworkInterfaces) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vmxnet3networkinterfacesResource, c.ns, name, opts), &v1alpha1.VMXNET3NetworkInterface{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVMXNET3NetworkInterfaces) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vmxnet3networkinterfacesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VMXNET3NetworkInterfaceList{})
	return err
}

// Patch applies the patch and returns the patched vMXNET3NetworkInterface.
func (c *FakeVMXNET3NetworkInterfaces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vmxnet3networkinterfacesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VMXNET3NetworkInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMXNET3NetworkInterface), err
}
