// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by informer-gen. DO NOT EDIT.

package informers_generated

import (
	"fmt"

	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=netoperator.vmware.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("aviloadbalancerconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().AviLoadBalancerConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("foundationloadbalancerconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().FoundationLoadBalancerConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("haproxyloadbalancerconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().HAProxyLoadBalancerConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ipaddressallocations"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().IPAddressAllocations().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ippools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().IPPools().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("loadbalancerconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().LoadBalancerConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("namespacenetworkconfigurations"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().NamespaceNetworkConfigurations().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("networks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().Networks().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("networkinterfaces"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().NetworkInterfaces().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("networksettingses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().NetworkSettingses().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("vmxnet3networkinterfaces"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().VMXNET3NetworkInterfaces().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("vspheredistributednetworks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().VSphereDistributedNetworks().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("workloadnetworkconfigurations"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Netoperator().V1alpha1().WorkloadNetworkConfigurations().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
