// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	scheme "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AviLoadBalancerConfigsGetter has a method to return a AviLoadBalancerConfigInterface.
// A group's client should implement this interface.
type AviLoadBalancerConfigsGetter interface {
	AviLoadBalancerConfigs() AviLoadBalancerConfigInterface
}

// AviLoadBalancerConfigInterface has methods to work with AviLoadBalancerConfig resources.
type AviLoadBalancerConfigInterface interface {
	Create(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.CreateOptions) (*v1alpha1.AviLoadBalancerConfig, error)
	Update(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.UpdateOptions) (*v1alpha1.AviLoadBalancerConfig, error)
	UpdateStatus(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.UpdateOptions) (*v1alpha1.AviLoadBalancerConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AviLoadBalancerConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AviLoadBalancerConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AviLoadBalancerConfig, err error)
	AviLoadBalancerConfigExpansion
}

// aviLoadBalancerConfigs implements AviLoadBalancerConfigInterface
type aviLoadBalancerConfigs struct {
	client rest.Interface
}

// newAviLoadBalancerConfigs returns a AviLoadBalancerConfigs
func newAviLoadBalancerConfigs(c *NetoperatorV1alpha1Client) *aviLoadBalancerConfigs {
	return &aviLoadBalancerConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the aviLoadBalancerConfig, and returns the corresponding aviLoadBalancerConfig object, and an error if there is any.
func (c *aviLoadBalancerConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	result = &v1alpha1.AviLoadBalancerConfig{}
	err = c.client.Get().
		Resource("aviloadbalancerconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AviLoadBalancerConfigs that match those selectors.
func (c *aviLoadBalancerConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AviLoadBalancerConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AviLoadBalancerConfigList{}
	err = c.client.Get().
		Resource("aviloadbalancerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aviLoadBalancerConfigs.
func (c *aviLoadBalancerConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("aviloadbalancerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aviLoadBalancerConfig and creates it.  Returns the server's representation of the aviLoadBalancerConfig, and an error, if there is any.
func (c *aviLoadBalancerConfigs) Create(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.CreateOptions) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	result = &v1alpha1.AviLoadBalancerConfig{}
	err = c.client.Post().
		Resource("aviloadbalancerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aviLoadBalancerConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aviLoadBalancerConfig and updates it. Returns the server's representation of the aviLoadBalancerConfig, and an error, if there is any.
func (c *aviLoadBalancerConfigs) Update(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.UpdateOptions) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	result = &v1alpha1.AviLoadBalancerConfig{}
	err = c.client.Put().
		Resource("aviloadbalancerconfigs").
		Name(aviLoadBalancerConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aviLoadBalancerConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aviLoadBalancerConfigs) UpdateStatus(ctx context.Context, aviLoadBalancerConfig *v1alpha1.AviLoadBalancerConfig, opts v1.UpdateOptions) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	result = &v1alpha1.AviLoadBalancerConfig{}
	err = c.client.Put().
		Resource("aviloadbalancerconfigs").
		Name(aviLoadBalancerConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aviLoadBalancerConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aviLoadBalancerConfig and deletes it. Returns an error if one occurs.
func (c *aviLoadBalancerConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("aviloadbalancerconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aviLoadBalancerConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("aviloadbalancerconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aviLoadBalancerConfig.
func (c *aviLoadBalancerConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AviLoadBalancerConfig, err error) {
	result = &v1alpha1.AviLoadBalancerConfig{}
	err = c.client.Patch(pt).
		Resource("aviloadbalancerconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
