// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AviLoadBalancerConfigExpansion interface{}

type FoundationLoadBalancerConfigExpansion interface{}

type HAProxyLoadBalancerConfigExpansion interface{}

type IPAddressAllocationExpansion interface{}

type IPPoolExpansion interface{}

type LoadBalancerConfigExpansion interface{}

type NamespaceNetworkConfigurationExpansion interface{}

type NetworkExpansion interface{}

type NetworkInterfaceExpansion interface{}

type NetworkSettingsExpansion interface{}

type VMXNET3NetworkInterfaceExpansion interface{}

type VSphereDistributedNetworkExpansion interface{}

type WorkloadNetworkConfigurationExpansion interface{}
