// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	scheme "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LoadBalancerConfigsGetter has a method to return a LoadBalancerConfigInterface.
// A group's client should implement this interface.
type LoadBalancerConfigsGetter interface {
	LoadBalancerConfigs() LoadBalancerConfigInterface
}

// LoadBalancerConfigInterface has methods to work with LoadBalancerConfig resources.
type LoadBalancerConfigInterface interface {
	Create(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.CreateOptions) (*v1alpha1.LoadBalancerConfig, error)
	Update(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.UpdateOptions) (*v1alpha1.LoadBalancerConfig, error)
	UpdateStatus(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.UpdateOptions) (*v1alpha1.LoadBalancerConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LoadBalancerConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LoadBalancerConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LoadBalancerConfig, err error)
	LoadBalancerConfigExpansion
}

// loadBalancerConfigs implements LoadBalancerConfigInterface
type loadBalancerConfigs struct {
	client rest.Interface
}

// newLoadBalancerConfigs returns a LoadBalancerConfigs
func newLoadBalancerConfigs(c *NetoperatorV1alpha1Client) *loadBalancerConfigs {
	return &loadBalancerConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the loadBalancerConfig, and returns the corresponding loadBalancerConfig object, and an error if there is any.
func (c *loadBalancerConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LoadBalancerConfig, err error) {
	result = &v1alpha1.LoadBalancerConfig{}
	err = c.client.Get().
		Resource("loadbalancerconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LoadBalancerConfigs that match those selectors.
func (c *loadBalancerConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LoadBalancerConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LoadBalancerConfigList{}
	err = c.client.Get().
		Resource("loadbalancerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested loadBalancerConfigs.
func (c *loadBalancerConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("loadbalancerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a loadBalancerConfig and creates it.  Returns the server's representation of the loadBalancerConfig, and an error, if there is any.
func (c *loadBalancerConfigs) Create(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.CreateOptions) (result *v1alpha1.LoadBalancerConfig, err error) {
	result = &v1alpha1.LoadBalancerConfig{}
	err = c.client.Post().
		Resource("loadbalancerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(loadBalancerConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a loadBalancerConfig and updates it. Returns the server's representation of the loadBalancerConfig, and an error, if there is any.
func (c *loadBalancerConfigs) Update(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.UpdateOptions) (result *v1alpha1.LoadBalancerConfig, err error) {
	result = &v1alpha1.LoadBalancerConfig{}
	err = c.client.Put().
		Resource("loadbalancerconfigs").
		Name(loadBalancerConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(loadBalancerConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *loadBalancerConfigs) UpdateStatus(ctx context.Context, loadBalancerConfig *v1alpha1.LoadBalancerConfig, opts v1.UpdateOptions) (result *v1alpha1.LoadBalancerConfig, err error) {
	result = &v1alpha1.LoadBalancerConfig{}
	err = c.client.Put().
		Resource("loadbalancerconfigs").
		Name(loadBalancerConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(loadBalancerConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the loadBalancerConfig and deletes it. Returns an error if one occurs.
func (c *loadBalancerConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("loadbalancerconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *loadBalancerConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("loadbalancerconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched loadBalancerConfig.
func (c *loadBalancerConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LoadBalancerConfig, err error) {
	result = &v1alpha1.LoadBalancerConfig{}
	err = c.client.Patch(pt).
		Resource("loadbalancerconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
