// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	scheme "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkSettingsesGetter has a method to return a NetworkSettingsInterface.
// A group's client should implement this interface.
type NetworkSettingsesGetter interface {
	NetworkSettingses(namespace string) NetworkSettingsInterface
}

// NetworkSettingsInterface has methods to work with NetworkSettings resources.
type NetworkSettingsInterface interface {
	Create(ctx context.Context, networkSettings *v1alpha1.NetworkSettings, opts v1.CreateOptions) (*v1alpha1.NetworkSettings, error)
	Update(ctx context.Context, networkSettings *v1alpha1.NetworkSettings, opts v1.UpdateOptions) (*v1alpha1.NetworkSettings, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NetworkSettings, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NetworkSettingsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkSettings, err error)
	NetworkSettingsExpansion
}

// networkSettingses implements NetworkSettingsInterface
type networkSettingses struct {
	client rest.Interface
	ns     string
}

// newNetworkSettingses returns a NetworkSettingses
func newNetworkSettingses(c *NetoperatorV1alpha1Client, namespace string) *networkSettingses {
	return &networkSettingses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the networkSettings, and returns the corresponding networkSettings object, and an error if there is any.
func (c *networkSettingses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkSettings, err error) {
	result = &v1alpha1.NetworkSettings{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networksettingses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkSettingses that match those selectors.
func (c *networkSettingses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkSettingsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NetworkSettingsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networksettingses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkSettingses.
func (c *networkSettingses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("networksettingses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a networkSettings and creates it.  Returns the server's representation of the networkSettings, and an error, if there is any.
func (c *networkSettingses) Create(ctx context.Context, networkSettings *v1alpha1.NetworkSettings, opts v1.CreateOptions) (result *v1alpha1.NetworkSettings, err error) {
	result = &v1alpha1.NetworkSettings{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("networksettingses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkSettings).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a networkSettings and updates it. Returns the server's representation of the networkSettings, and an error, if there is any.
func (c *networkSettingses) Update(ctx context.Context, networkSettings *v1alpha1.NetworkSettings, opts v1.UpdateOptions) (result *v1alpha1.NetworkSettings, err error) {
	result = &v1alpha1.NetworkSettings{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networksettingses").
		Name(networkSettings.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkSettings).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the networkSettings and deletes it. Returns an error if one occurs.
func (c *networkSettingses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networksettingses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkSettingses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networksettingses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched networkSettings.
func (c *networkSettingses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkSettings, err error) {
	result = &v1alpha1.NetworkSettings{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("networksettingses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
