// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	scheme "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VMXNET3NetworkInterfacesGetter has a method to return a VMXNET3NetworkInterfaceInterface.
// A group's client should implement this interface.
type VMXNET3NetworkInterfacesGetter interface {
	VMXNET3NetworkInterfaces(namespace string) VMXNET3NetworkInterfaceInterface
}

// VMXNET3NetworkInterfaceInterface has methods to work with VMXNET3NetworkInterface resources.
type VMXNET3NetworkInterfaceInterface interface {
	Create(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.CreateOptions) (*v1alpha1.VMXNET3NetworkInterface, error)
	Update(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.UpdateOptions) (*v1alpha1.VMXNET3NetworkInterface, error)
	UpdateStatus(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.UpdateOptions) (*v1alpha1.VMXNET3NetworkInterface, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VMXNET3NetworkInterface, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VMXNET3NetworkInterfaceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VMXNET3NetworkInterface, err error)
	VMXNET3NetworkInterfaceExpansion
}

// vMXNET3NetworkInterfaces implements VMXNET3NetworkInterfaceInterface
type vMXNET3NetworkInterfaces struct {
	client rest.Interface
	ns     string
}

// newVMXNET3NetworkInterfaces returns a VMXNET3NetworkInterfaces
func newVMXNET3NetworkInterfaces(c *NetoperatorV1alpha1Client, namespace string) *vMXNET3NetworkInterfaces {
	return &vMXNET3NetworkInterfaces{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vMXNET3NetworkInterface, and returns the corresponding vMXNET3NetworkInterface object, and an error if there is any.
func (c *vMXNET3NetworkInterfaces) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	result = &v1alpha1.VMXNET3NetworkInterface{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VMXNET3NetworkInterfaces that match those selectors.
func (c *vMXNET3NetworkInterfaces) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VMXNET3NetworkInterfaceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VMXNET3NetworkInterfaceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vMXNET3NetworkInterfaces.
func (c *vMXNET3NetworkInterfaces) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vMXNET3NetworkInterface and creates it.  Returns the server's representation of the vMXNET3NetworkInterface, and an error, if there is any.
func (c *vMXNET3NetworkInterfaces) Create(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.CreateOptions) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	result = &v1alpha1.VMXNET3NetworkInterface{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMXNET3NetworkInterface).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vMXNET3NetworkInterface and updates it. Returns the server's representation of the vMXNET3NetworkInterface, and an error, if there is any.
func (c *vMXNET3NetworkInterfaces) Update(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.UpdateOptions) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	result = &v1alpha1.VMXNET3NetworkInterface{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		Name(vMXNET3NetworkInterface.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMXNET3NetworkInterface).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vMXNET3NetworkInterfaces) UpdateStatus(ctx context.Context, vMXNET3NetworkInterface *v1alpha1.VMXNET3NetworkInterface, opts v1.UpdateOptions) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	result = &v1alpha1.VMXNET3NetworkInterface{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		Name(vMXNET3NetworkInterface.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMXNET3NetworkInterface).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vMXNET3NetworkInterface and deletes it. Returns an error if one occurs.
func (c *vMXNET3NetworkInterfaces) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vMXNET3NetworkInterfaces) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vMXNET3NetworkInterface.
func (c *vMXNET3NetworkInterfaces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VMXNET3NetworkInterface, err error) {
	result = &v1alpha1.VMXNET3NetworkInterface{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vmxnet3networkinterfaces").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
