// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	scheme "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VSphereDistributedNetworksGetter has a method to return a VSphereDistributedNetworkInterface.
// A group's client should implement this interface.
type VSphereDistributedNetworksGetter interface {
	VSphereDistributedNetworks() VSphereDistributedNetworkInterface
}

// VSphereDistributedNetworkInterface has methods to work with VSphereDistributedNetwork resources.
type VSphereDistributedNetworkInterface interface {
	Create(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.CreateOptions) (*v1alpha1.VSphereDistributedNetwork, error)
	Update(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.UpdateOptions) (*v1alpha1.VSphereDistributedNetwork, error)
	UpdateStatus(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.UpdateOptions) (*v1alpha1.VSphereDistributedNetwork, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VSphereDistributedNetwork, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VSphereDistributedNetworkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VSphereDistributedNetwork, err error)
	VSphereDistributedNetworkExpansion
}

// vSphereDistributedNetworks implements VSphereDistributedNetworkInterface
type vSphereDistributedNetworks struct {
	client rest.Interface
}

// newVSphereDistributedNetworks returns a VSphereDistributedNetworks
func newVSphereDistributedNetworks(c *NetoperatorV1alpha1Client) *vSphereDistributedNetworks {
	return &vSphereDistributedNetworks{
		client: c.RESTClient(),
	}
}

// Get takes name of the vSphereDistributedNetwork, and returns the corresponding vSphereDistributedNetwork object, and an error if there is any.
func (c *vSphereDistributedNetworks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	result = &v1alpha1.VSphereDistributedNetwork{}
	err = c.client.Get().
		Resource("vspheredistributednetworks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VSphereDistributedNetworks that match those selectors.
func (c *vSphereDistributedNetworks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VSphereDistributedNetworkList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VSphereDistributedNetworkList{}
	err = c.client.Get().
		Resource("vspheredistributednetworks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vSphereDistributedNetworks.
func (c *vSphereDistributedNetworks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("vspheredistributednetworks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vSphereDistributedNetwork and creates it.  Returns the server's representation of the vSphereDistributedNetwork, and an error, if there is any.
func (c *vSphereDistributedNetworks) Create(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.CreateOptions) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	result = &v1alpha1.VSphereDistributedNetwork{}
	err = c.client.Post().
		Resource("vspheredistributednetworks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereDistributedNetwork).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vSphereDistributedNetwork and updates it. Returns the server's representation of the vSphereDistributedNetwork, and an error, if there is any.
func (c *vSphereDistributedNetworks) Update(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.UpdateOptions) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	result = &v1alpha1.VSphereDistributedNetwork{}
	err = c.client.Put().
		Resource("vspheredistributednetworks").
		Name(vSphereDistributedNetwork.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereDistributedNetwork).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vSphereDistributedNetworks) UpdateStatus(ctx context.Context, vSphereDistributedNetwork *v1alpha1.VSphereDistributedNetwork, opts v1.UpdateOptions) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	result = &v1alpha1.VSphereDistributedNetwork{}
	err = c.client.Put().
		Resource("vspheredistributednetworks").
		Name(vSphereDistributedNetwork.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vSphereDistributedNetwork).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vSphereDistributedNetwork and deletes it. Returns an error if one occurs.
func (c *vSphereDistributedNetworks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("vspheredistributednetworks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vSphereDistributedNetworks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("vspheredistributednetworks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vSphereDistributedNetwork.
func (c *vSphereDistributedNetworks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VSphereDistributedNetwork, err error) {
	result = &v1alpha1.VSphereDistributedNetwork{}
	err = c.client.Patch(pt).
		Resource("vspheredistributednetworks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
