// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	scheme "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WorkloadNetworkConfigurationsGetter has a method to return a WorkloadNetworkConfigurationInterface.
// A group's client should implement this interface.
type WorkloadNetworkConfigurationsGetter interface {
	WorkloadNetworkConfigurations() WorkloadNetworkConfigurationInterface
}

// WorkloadNetworkConfigurationInterface has methods to work with WorkloadNetworkConfiguration resources.
type WorkloadNetworkConfigurationInterface interface {
	Create(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.CreateOptions) (*v1alpha1.WorkloadNetworkConfiguration, error)
	Update(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.UpdateOptions) (*v1alpha1.WorkloadNetworkConfiguration, error)
	UpdateStatus(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.UpdateOptions) (*v1alpha1.WorkloadNetworkConfiguration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.WorkloadNetworkConfiguration, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.WorkloadNetworkConfigurationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkloadNetworkConfiguration, err error)
	WorkloadNetworkConfigurationExpansion
}

// workloadNetworkConfigurations implements WorkloadNetworkConfigurationInterface
type workloadNetworkConfigurations struct {
	client rest.Interface
}

// newWorkloadNetworkConfigurations returns a WorkloadNetworkConfigurations
func newWorkloadNetworkConfigurations(c *NetoperatorV1alpha1Client) *workloadNetworkConfigurations {
	return &workloadNetworkConfigurations{
		client: c.RESTClient(),
	}
}

// Get takes name of the workloadNetworkConfiguration, and returns the corresponding workloadNetworkConfiguration object, and an error if there is any.
func (c *workloadNetworkConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	result = &v1alpha1.WorkloadNetworkConfiguration{}
	err = c.client.Get().
		Resource("workloadnetworkconfigurations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkloadNetworkConfigurations that match those selectors.
func (c *workloadNetworkConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkloadNetworkConfigurationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WorkloadNetworkConfigurationList{}
	err = c.client.Get().
		Resource("workloadnetworkconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workloadNetworkConfigurations.
func (c *workloadNetworkConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("workloadnetworkconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a workloadNetworkConfiguration and creates it.  Returns the server's representation of the workloadNetworkConfiguration, and an error, if there is any.
func (c *workloadNetworkConfigurations) Create(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.CreateOptions) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	result = &v1alpha1.WorkloadNetworkConfiguration{}
	err = c.client.Post().
		Resource("workloadnetworkconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workloadNetworkConfiguration).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a workloadNetworkConfiguration and updates it. Returns the server's representation of the workloadNetworkConfiguration, and an error, if there is any.
func (c *workloadNetworkConfigurations) Update(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.UpdateOptions) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	result = &v1alpha1.WorkloadNetworkConfiguration{}
	err = c.client.Put().
		Resource("workloadnetworkconfigurations").
		Name(workloadNetworkConfiguration.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workloadNetworkConfiguration).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *workloadNetworkConfigurations) UpdateStatus(ctx context.Context, workloadNetworkConfiguration *v1alpha1.WorkloadNetworkConfiguration, opts v1.UpdateOptions) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	result = &v1alpha1.WorkloadNetworkConfiguration{}
	err = c.client.Put().
		Resource("workloadnetworkconfigurations").
		Name(workloadNetworkConfiguration.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workloadNetworkConfiguration).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the workloadNetworkConfiguration and deletes it. Returns an error if one occurs.
func (c *workloadNetworkConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("workloadnetworkconfigurations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workloadNetworkConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("workloadnetworkconfigurations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched workloadNetworkConfiguration.
func (c *workloadNetworkConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkloadNetworkConfiguration, err error) {
	result = &v1alpha1.WorkloadNetworkConfiguration{}
	err = c.client.Patch(pt).
		Resource("workloadnetworkconfigurations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
