// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/vmware-tanzu/net-operator-api/pkg/client/informers_generated/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AviLoadBalancerConfigs returns a AviLoadBalancerConfigInformer.
	AviLoadBalancerConfigs() AviLoadBalancerConfigInformer
	// FoundationLoadBalancerConfigs returns a FoundationLoadBalancerConfigInformer.
	FoundationLoadBalancerConfigs() FoundationLoadBalancerConfigInformer
	// HAProxyLoadBalancerConfigs returns a HAProxyLoadBalancerConfigInformer.
	HAProxyLoadBalancerConfigs() HAProxyLoadBalancerConfigInformer
	// IPAddressAllocations returns a IPAddressAllocationInformer.
	IPAddressAllocations() IPAddressAllocationInformer
	// IPPools returns a IPPoolInformer.
	IPPools() IPPoolInformer
	// LoadBalancerConfigs returns a LoadBalancerConfigInformer.
	LoadBalancerConfigs() LoadBalancerConfigInformer
	// NamespaceNetworkConfigurations returns a NamespaceNetworkConfigurationInformer.
	NamespaceNetworkConfigurations() NamespaceNetworkConfigurationInformer
	// Networks returns a NetworkInformer.
	Networks() NetworkInformer
	// NetworkInterfaces returns a NetworkInterfaceInformer.
	NetworkInterfaces() NetworkInterfaceInformer
	// NetworkSettingses returns a NetworkSettingsInformer.
	NetworkSettingses() NetworkSettingsInformer
	// VMXNET3NetworkInterfaces returns a VMXNET3NetworkInterfaceInformer.
	VMXNET3NetworkInterfaces() VMXNET3NetworkInterfaceInformer
	// VSphereDistributedNetworks returns a VSphereDistributedNetworkInformer.
	VSphereDistributedNetworks() VSphereDistributedNetworkInformer
	// WorkloadNetworkConfigurations returns a WorkloadNetworkConfigurationInformer.
	WorkloadNetworkConfigurations() WorkloadNetworkConfigurationInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AviLoadBalancerConfigs returns a AviLoadBalancerConfigInformer.
func (v *version) AviLoadBalancerConfigs() AviLoadBalancerConfigInformer {
	return &aviLoadBalancerConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// FoundationLoadBalancerConfigs returns a FoundationLoadBalancerConfigInformer.
func (v *version) FoundationLoadBalancerConfigs() FoundationLoadBalancerConfigInformer {
	return &foundationLoadBalancerConfigInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// HAProxyLoadBalancerConfigs returns a HAProxyLoadBalancerConfigInformer.
func (v *version) HAProxyLoadBalancerConfigs() HAProxyLoadBalancerConfigInformer {
	return &hAProxyLoadBalancerConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IPAddressAllocations returns a IPAddressAllocationInformer.
func (v *version) IPAddressAllocations() IPAddressAllocationInformer {
	return &iPAddressAllocationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IPPools returns a IPPoolInformer.
func (v *version) IPPools() IPPoolInformer {
	return &iPPoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LoadBalancerConfigs returns a LoadBalancerConfigInformer.
func (v *version) LoadBalancerConfigs() LoadBalancerConfigInformer {
	return &loadBalancerConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// NamespaceNetworkConfigurations returns a NamespaceNetworkConfigurationInformer.
func (v *version) NamespaceNetworkConfigurations() NamespaceNetworkConfigurationInformer {
	return &namespaceNetworkConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Networks returns a NetworkInformer.
func (v *version) Networks() NetworkInformer {
	return &networkInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NetworkInterfaces returns a NetworkInterfaceInformer.
func (v *version) NetworkInterfaces() NetworkInterfaceInformer {
	return &networkInterfaceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NetworkSettingses returns a NetworkSettingsInformer.
func (v *version) NetworkSettingses() NetworkSettingsInformer {
	return &networkSettingsInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VMXNET3NetworkInterfaces returns a VMXNET3NetworkInterfaceInformer.
func (v *version) VMXNET3NetworkInterfaces() VMXNET3NetworkInterfaceInformer {
	return &vMXNET3NetworkInterfaceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VSphereDistributedNetworks returns a VSphereDistributedNetworkInformer.
func (v *version) VSphereDistributedNetworks() VSphereDistributedNetworkInformer {
	return &vSphereDistributedNetworkInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// WorkloadNetworkConfigurations returns a WorkloadNetworkConfigurationInformer.
func (v *version) WorkloadNetworkConfigurations() WorkloadNetworkConfigurationInformer {
	return &workloadNetworkConfigurationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
