// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	apiv1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	clientset "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/vmware-tanzu/net-operator-api/pkg/client/informers_generated/internalinterfaces"
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/pkg/client/listers_generated/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LoadBalancerConfigInformer provides access to a shared informer and lister for
// LoadBalancerConfigs.
type LoadBalancerConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.LoadBalancerConfigLister
}

type loadBalancerConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewLoadBalancerConfigInformer constructs a new informer for LoadBalancerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLoadBalancerConfigInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLoadBalancerConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredLoadBalancerConfigInformer constructs a new informer for LoadBalancerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLoadBalancerConfigInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetoperatorV1alpha1().LoadBalancerConfigs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetoperatorV1alpha1().LoadBalancerConfigs().Watch(context.TODO(), options)
			},
		},
		&apiv1alpha1.LoadBalancerConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *loadBalancerConfigInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLoadBalancerConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *loadBalancerConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiv1alpha1.LoadBalancerConfig{}, f.defaultInformer)
}

func (f *loadBalancerConfigInformer) Lister() v1alpha1.LoadBalancerConfigLister {
	return v1alpha1.NewLoadBalancerConfigLister(f.Informer().GetIndexer())
}
