// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	apiv1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	clientset "github.com/vmware-tanzu/net-operator-api/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/vmware-tanzu/net-operator-api/pkg/client/informers_generated/internalinterfaces"
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/pkg/client/listers_generated/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VMXNET3NetworkInterfaceInformer provides access to a shared informer and lister for
// VMXNET3NetworkInterfaces.
type VMXNET3NetworkInterfaceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VMXNET3NetworkInterfaceLister
}

type vMXNET3NetworkInterfaceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVMXNET3NetworkInterfaceInformer constructs a new informer for VMXNET3NetworkInterface type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVMXNET3NetworkInterfaceInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVMXNET3NetworkInterfaceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVMXNET3NetworkInterfaceInformer constructs a new informer for VMXNET3NetworkInterface type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVMXNET3NetworkInterfaceInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetoperatorV1alpha1().VMXNET3NetworkInterfaces(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetoperatorV1alpha1().VMXNET3NetworkInterfaces(namespace).Watch(context.TODO(), options)
			},
		},
		&apiv1alpha1.VMXNET3NetworkInterface{},
		resyncPeriod,
		indexers,
	)
}

func (f *vMXNET3NetworkInterfaceInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVMXNET3NetworkInterfaceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vMXNET3NetworkInterfaceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiv1alpha1.VMXNET3NetworkInterface{}, f.defaultInformer)
}

func (f *vMXNET3NetworkInterfaceInformer) Lister() v1alpha1.VMXNET3NetworkInterfaceLister {
	return v1alpha1.NewVMXNET3NetworkInterfaceLister(f.Informer().GetIndexer())
}
