// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AviLoadBalancerConfigLister helps list AviLoadBalancerConfigs.
// All objects returned here must be treated as read-only.
type AviLoadBalancerConfigLister interface {
	// List lists all AviLoadBalancerConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AviLoadBalancerConfig, err error)
	// Get retrieves the AviLoadBalancerConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.AviLoadBalancerConfig, error)
	AviLoadBalancerConfigListerExpansion
}

// aviLoadBalancerConfigLister implements the AviLoadBalancerConfigLister interface.
type aviLoadBalancerConfigLister struct {
	indexer cache.Indexer
}

// NewAviLoadBalancerConfigLister returns a new AviLoadBalancerConfigLister.
func NewAviLoadBalancerConfigLister(indexer cache.Indexer) AviLoadBalancerConfigLister {
	return &aviLoadBalancerConfigLister{indexer: indexer}
}

// List lists all AviLoadBalancerConfigs in the indexer.
func (s *aviLoadBalancerConfigLister) List(selector labels.Selector) (ret []*v1alpha1.AviLoadBalancerConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AviLoadBalancerConfig))
	})
	return ret, err
}

// Get retrieves the AviLoadBalancerConfig from the index for a given name.
func (s *aviLoadBalancerConfigLister) Get(name string) (*v1alpha1.AviLoadBalancerConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("aviloadbalancerconfig"), name)
	}
	return obj.(*v1alpha1.AviLoadBalancerConfig), nil
}
