// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AviLoadBalancerConfigListerExpansion allows custom methods to be added to
// AviLoadBalancerConfigLister.
type AviLoadBalancerConfigListerExpansion interface{}

// FoundationLoadBalancerConfigListerExpansion allows custom methods to be added to
// FoundationLoadBalancerConfigLister.
type FoundationLoadBalancerConfigListerExpansion interface{}

// FoundationLoadBalancerConfigNamespaceListerExpansion allows custom methods to be added to
// FoundationLoadBalancerConfigNamespaceLister.
type FoundationLoadBalancerConfigNamespaceListerExpansion interface{}

// HAProxyLoadBalancerConfigListerExpansion allows custom methods to be added to
// HAProxyLoadBalancerConfigLister.
type HAProxyLoadBalancerConfigListerExpansion interface{}

// IPAddressAllocationListerExpansion allows custom methods to be added to
// IPAddressAllocationLister.
type IPAddressAllocationListerExpansion interface{}

// IPAddressAllocationNamespaceListerExpansion allows custom methods to be added to
// IPAddressAllocationNamespaceLister.
type IPAddressAllocationNamespaceListerExpansion interface{}

// IPPoolListerExpansion allows custom methods to be added to
// IPPoolLister.
type IPPoolListerExpansion interface{}

// LoadBalancerConfigListerExpansion allows custom methods to be added to
// LoadBalancerConfigLister.
type LoadBalancerConfigListerExpansion interface{}

// NamespaceNetworkConfigurationListerExpansion allows custom methods to be added to
// NamespaceNetworkConfigurationLister.
type NamespaceNetworkConfigurationListerExpansion interface{}

// NetworkListerExpansion allows custom methods to be added to
// NetworkLister.
type NetworkListerExpansion interface{}

// NetworkNamespaceListerExpansion allows custom methods to be added to
// NetworkNamespaceLister.
type NetworkNamespaceListerExpansion interface{}

// NetworkInterfaceListerExpansion allows custom methods to be added to
// NetworkInterfaceLister.
type NetworkInterfaceListerExpansion interface{}

// NetworkInterfaceNamespaceListerExpansion allows custom methods to be added to
// NetworkInterfaceNamespaceLister.
type NetworkInterfaceNamespaceListerExpansion interface{}

// NetworkSettingsListerExpansion allows custom methods to be added to
// NetworkSettingsLister.
type NetworkSettingsListerExpansion interface{}

// NetworkSettingsNamespaceListerExpansion allows custom methods to be added to
// NetworkSettingsNamespaceLister.
type NetworkSettingsNamespaceListerExpansion interface{}

// VMXNET3NetworkInterfaceListerExpansion allows custom methods to be added to
// VMXNET3NetworkInterfaceLister.
type VMXNET3NetworkInterfaceListerExpansion interface{}

// VMXNET3NetworkInterfaceNamespaceListerExpansion allows custom methods to be added to
// VMXNET3NetworkInterfaceNamespaceLister.
type VMXNET3NetworkInterfaceNamespaceListerExpansion interface{}

// VSphereDistributedNetworkListerExpansion allows custom methods to be added to
// VSphereDistributedNetworkLister.
type VSphereDistributedNetworkListerExpansion interface{}

// WorkloadNetworkConfigurationListerExpansion allows custom methods to be added to
// WorkloadNetworkConfigurationLister.
type WorkloadNetworkConfigurationListerExpansion interface{}
