// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FoundationLoadBalancerConfigLister helps list FoundationLoadBalancerConfigs.
// All objects returned here must be treated as read-only.
type FoundationLoadBalancerConfigLister interface {
	// List lists all FoundationLoadBalancerConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FoundationLoadBalancerConfig, err error)
	// FoundationLoadBalancerConfigs returns an object that can list and get FoundationLoadBalancerConfigs.
	FoundationLoadBalancerConfigs(namespace string) FoundationLoadBalancerConfigNamespaceLister
	FoundationLoadBalancerConfigListerExpansion
}

// foundationLoadBalancerConfigLister implements the FoundationLoadBalancerConfigLister interface.
type foundationLoadBalancerConfigLister struct {
	indexer cache.Indexer
}

// NewFoundationLoadBalancerConfigLister returns a new FoundationLoadBalancerConfigLister.
func NewFoundationLoadBalancerConfigLister(indexer cache.Indexer) FoundationLoadBalancerConfigLister {
	return &foundationLoadBalancerConfigLister{indexer: indexer}
}

// List lists all FoundationLoadBalancerConfigs in the indexer.
func (s *foundationLoadBalancerConfigLister) List(selector labels.Selector) (ret []*v1alpha1.FoundationLoadBalancerConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FoundationLoadBalancerConfig))
	})
	return ret, err
}

// FoundationLoadBalancerConfigs returns an object that can list and get FoundationLoadBalancerConfigs.
func (s *foundationLoadBalancerConfigLister) FoundationLoadBalancerConfigs(namespace string) FoundationLoadBalancerConfigNamespaceLister {
	return foundationLoadBalancerConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FoundationLoadBalancerConfigNamespaceLister helps list and get FoundationLoadBalancerConfigs.
// All objects returned here must be treated as read-only.
type FoundationLoadBalancerConfigNamespaceLister interface {
	// List lists all FoundationLoadBalancerConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FoundationLoadBalancerConfig, err error)
	// Get retrieves the FoundationLoadBalancerConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FoundationLoadBalancerConfig, error)
	FoundationLoadBalancerConfigNamespaceListerExpansion
}

// foundationLoadBalancerConfigNamespaceLister implements the FoundationLoadBalancerConfigNamespaceLister
// interface.
type foundationLoadBalancerConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FoundationLoadBalancerConfigs in the indexer for a given namespace.
func (s foundationLoadBalancerConfigNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.FoundationLoadBalancerConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FoundationLoadBalancerConfig))
	})
	return ret, err
}

// Get retrieves the FoundationLoadBalancerConfig from the indexer for a given namespace and name.
func (s foundationLoadBalancerConfigNamespaceLister) Get(name string) (*v1alpha1.FoundationLoadBalancerConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("foundationloadbalancerconfig"), name)
	}
	return obj.(*v1alpha1.FoundationLoadBalancerConfig), nil
}
