// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HAProxyLoadBalancerConfigLister helps list HAProxyLoadBalancerConfigs.
// All objects returned here must be treated as read-only.
type HAProxyLoadBalancerConfigLister interface {
	// List lists all HAProxyLoadBalancerConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HAProxyLoadBalancerConfig, err error)
	// Get retrieves the HAProxyLoadBalancerConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.HAProxyLoadBalancerConfig, error)
	HAProxyLoadBalancerConfigListerExpansion
}

// hAProxyLoadBalancerConfigLister implements the HAProxyLoadBalancerConfigLister interface.
type hAProxyLoadBalancerConfigLister struct {
	indexer cache.Indexer
}

// NewHAProxyLoadBalancerConfigLister returns a new HAProxyLoadBalancerConfigLister.
func NewHAProxyLoadBalancerConfigLister(indexer cache.Indexer) HAProxyLoadBalancerConfigLister {
	return &hAProxyLoadBalancerConfigLister{indexer: indexer}
}

// List lists all HAProxyLoadBalancerConfigs in the indexer.
func (s *hAProxyLoadBalancerConfigLister) List(selector labels.Selector) (ret []*v1alpha1.HAProxyLoadBalancerConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HAProxyLoadBalancerConfig))
	})
	return ret, err
}

// Get retrieves the HAProxyLoadBalancerConfig from the index for a given name.
func (s *hAProxyLoadBalancerConfigLister) Get(name string) (*v1alpha1.HAProxyLoadBalancerConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("haproxyloadbalancerconfig"), name)
	}
	return obj.(*v1alpha1.HAProxyLoadBalancerConfig), nil
}
