// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LoadBalancerConfigLister helps list LoadBalancerConfigs.
// All objects returned here must be treated as read-only.
type LoadBalancerConfigLister interface {
	// List lists all LoadBalancerConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LoadBalancerConfig, err error)
	// Get retrieves the LoadBalancerConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.LoadBalancerConfig, error)
	LoadBalancerConfigListerExpansion
}

// loadBalancerConfigLister implements the LoadBalancerConfigLister interface.
type loadBalancerConfigLister struct {
	indexer cache.Indexer
}

// NewLoadBalancerConfigLister returns a new LoadBalancerConfigLister.
func NewLoadBalancerConfigLister(indexer cache.Indexer) LoadBalancerConfigLister {
	return &loadBalancerConfigLister{indexer: indexer}
}

// List lists all LoadBalancerConfigs in the indexer.
func (s *loadBalancerConfigLister) List(selector labels.Selector) (ret []*v1alpha1.LoadBalancerConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LoadBalancerConfig))
	})
	return ret, err
}

// Get retrieves the LoadBalancerConfig from the index for a given name.
func (s *loadBalancerConfigLister) Get(name string) (*v1alpha1.LoadBalancerConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("loadbalancerconfig"), name)
	}
	return obj.(*v1alpha1.LoadBalancerConfig), nil
}
