// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NamespaceNetworkConfigurationLister helps list NamespaceNetworkConfigurations.
// All objects returned here must be treated as read-only.
type NamespaceNetworkConfigurationLister interface {
	// List lists all NamespaceNetworkConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NamespaceNetworkConfiguration, err error)
	// Get retrieves the NamespaceNetworkConfiguration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.NamespaceNetworkConfiguration, error)
	NamespaceNetworkConfigurationListerExpansion
}

// namespaceNetworkConfigurationLister implements the NamespaceNetworkConfigurationLister interface.
type namespaceNetworkConfigurationLister struct {
	indexer cache.Indexer
}

// NewNamespaceNetworkConfigurationLister returns a new NamespaceNetworkConfigurationLister.
func NewNamespaceNetworkConfigurationLister(indexer cache.Indexer) NamespaceNetworkConfigurationLister {
	return &namespaceNetworkConfigurationLister{indexer: indexer}
}

// List lists all NamespaceNetworkConfigurations in the indexer.
func (s *namespaceNetworkConfigurationLister) List(selector labels.Selector) (ret []*v1alpha1.NamespaceNetworkConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NamespaceNetworkConfiguration))
	})
	return ret, err
}

// Get retrieves the NamespaceNetworkConfiguration from the index for a given name.
func (s *namespaceNetworkConfigurationLister) Get(name string) (*v1alpha1.NamespaceNetworkConfiguration, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("namespacenetworkconfiguration"), name)
	}
	return obj.(*v1alpha1.NamespaceNetworkConfiguration), nil
}
