// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetworkSettingsLister helps list NetworkSettingses.
// All objects returned here must be treated as read-only.
type NetworkSettingsLister interface {
	// List lists all NetworkSettingses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NetworkSettings, err error)
	// NetworkSettingses returns an object that can list and get NetworkSettingses.
	NetworkSettingses(namespace string) NetworkSettingsNamespaceLister
	NetworkSettingsListerExpansion
}

// networkSettingsLister implements the NetworkSettingsLister interface.
type networkSettingsLister struct {
	indexer cache.Indexer
}

// NewNetworkSettingsLister returns a new NetworkSettingsLister.
func NewNetworkSettingsLister(indexer cache.Indexer) NetworkSettingsLister {
	return &networkSettingsLister{indexer: indexer}
}

// List lists all NetworkSettingses in the indexer.
func (s *networkSettingsLister) List(selector labels.Selector) (ret []*v1alpha1.NetworkSettings, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NetworkSettings))
	})
	return ret, err
}

// NetworkSettingses returns an object that can list and get NetworkSettingses.
func (s *networkSettingsLister) NetworkSettingses(namespace string) NetworkSettingsNamespaceLister {
	return networkSettingsNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NetworkSettingsNamespaceLister helps list and get NetworkSettingses.
// All objects returned here must be treated as read-only.
type NetworkSettingsNamespaceLister interface {
	// List lists all NetworkSettingses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NetworkSettings, err error)
	// Get retrieves the NetworkSettings from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.NetworkSettings, error)
	NetworkSettingsNamespaceListerExpansion
}

// networkSettingsNamespaceLister implements the NetworkSettingsNamespaceLister
// interface.
type networkSettingsNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NetworkSettingses in the indexer for a given namespace.
func (s networkSettingsNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.NetworkSettings, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NetworkSettings))
	})
	return ret, err
}

// Get retrieves the NetworkSettings from the indexer for a given namespace and name.
func (s networkSettingsNamespaceLister) Get(name string) (*v1alpha1.NetworkSettings, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("networksettings"), name)
	}
	return obj.(*v1alpha1.NetworkSettings), nil
}
