// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VMXNET3NetworkInterfaceLister helps list VMXNET3NetworkInterfaces.
// All objects returned here must be treated as read-only.
type VMXNET3NetworkInterfaceLister interface {
	// List lists all VMXNET3NetworkInterfaces in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.VMXNET3NetworkInterface, err error)
	// VMXNET3NetworkInterfaces returns an object that can list and get VMXNET3NetworkInterfaces.
	VMXNET3NetworkInterfaces(namespace string) VMXNET3NetworkInterfaceNamespaceLister
	VMXNET3NetworkInterfaceListerExpansion
}

// vMXNET3NetworkInterfaceLister implements the VMXNET3NetworkInterfaceLister interface.
type vMXNET3NetworkInterfaceLister struct {
	indexer cache.Indexer
}

// NewVMXNET3NetworkInterfaceLister returns a new VMXNET3NetworkInterfaceLister.
func NewVMXNET3NetworkInterfaceLister(indexer cache.Indexer) VMXNET3NetworkInterfaceLister {
	return &vMXNET3NetworkInterfaceLister{indexer: indexer}
}

// List lists all VMXNET3NetworkInterfaces in the indexer.
func (s *vMXNET3NetworkInterfaceLister) List(selector labels.Selector) (ret []*v1alpha1.VMXNET3NetworkInterface, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VMXNET3NetworkInterface))
	})
	return ret, err
}

// VMXNET3NetworkInterfaces returns an object that can list and get VMXNET3NetworkInterfaces.
func (s *vMXNET3NetworkInterfaceLister) VMXNET3NetworkInterfaces(namespace string) VMXNET3NetworkInterfaceNamespaceLister {
	return vMXNET3NetworkInterfaceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VMXNET3NetworkInterfaceNamespaceLister helps list and get VMXNET3NetworkInterfaces.
// All objects returned here must be treated as read-only.
type VMXNET3NetworkInterfaceNamespaceLister interface {
	// List lists all VMXNET3NetworkInterfaces in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.VMXNET3NetworkInterface, err error)
	// Get retrieves the VMXNET3NetworkInterface from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.VMXNET3NetworkInterface, error)
	VMXNET3NetworkInterfaceNamespaceListerExpansion
}

// vMXNET3NetworkInterfaceNamespaceLister implements the VMXNET3NetworkInterfaceNamespaceLister
// interface.
type vMXNET3NetworkInterfaceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VMXNET3NetworkInterfaces in the indexer for a given namespace.
func (s vMXNET3NetworkInterfaceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.VMXNET3NetworkInterface, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VMXNET3NetworkInterface))
	})
	return ret, err
}

// Get retrieves the VMXNET3NetworkInterface from the indexer for a given namespace and name.
func (s vMXNET3NetworkInterfaceNamespaceLister) Get(name string) (*v1alpha1.VMXNET3NetworkInterface, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("vmxnet3networkinterface"), name)
	}
	return obj.(*v1alpha1.VMXNET3NetworkInterface), nil
}
