// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VSphereDistributedNetworkLister helps list VSphereDistributedNetworks.
// All objects returned here must be treated as read-only.
type VSphereDistributedNetworkLister interface {
	// List lists all VSphereDistributedNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.VSphereDistributedNetwork, err error)
	// Get retrieves the VSphereDistributedNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.VSphereDistributedNetwork, error)
	VSphereDistributedNetworkListerExpansion
}

// vSphereDistributedNetworkLister implements the VSphereDistributedNetworkLister interface.
type vSphereDistributedNetworkLister struct {
	indexer cache.Indexer
}

// NewVSphereDistributedNetworkLister returns a new VSphereDistributedNetworkLister.
func NewVSphereDistributedNetworkLister(indexer cache.Indexer) VSphereDistributedNetworkLister {
	return &vSphereDistributedNetworkLister{indexer: indexer}
}

// List lists all VSphereDistributedNetworks in the indexer.
func (s *vSphereDistributedNetworkLister) List(selector labels.Selector) (ret []*v1alpha1.VSphereDistributedNetwork, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VSphereDistributedNetwork))
	})
	return ret, err
}

// Get retrieves the VSphereDistributedNetwork from the index for a given name.
func (s *vSphereDistributedNetworkLister) Get(name string) (*v1alpha1.VSphereDistributedNetwork, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("vspheredistributednetwork"), name)
	}
	return obj.(*v1alpha1.VSphereDistributedNetwork), nil
}
