// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/net-operator-api/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// WorkloadNetworkConfigurationLister helps list WorkloadNetworkConfigurations.
// All objects returned here must be treated as read-only.
type WorkloadNetworkConfigurationLister interface {
	// List lists all WorkloadNetworkConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.WorkloadNetworkConfiguration, err error)
	// Get retrieves the WorkloadNetworkConfiguration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.WorkloadNetworkConfiguration, error)
	WorkloadNetworkConfigurationListerExpansion
}

// workloadNetworkConfigurationLister implements the WorkloadNetworkConfigurationLister interface.
type workloadNetworkConfigurationLister struct {
	indexer cache.Indexer
}

// NewWorkloadNetworkConfigurationLister returns a new WorkloadNetworkConfigurationLister.
func NewWorkloadNetworkConfigurationLister(indexer cache.Indexer) WorkloadNetworkConfigurationLister {
	return &workloadNetworkConfigurationLister{indexer: indexer}
}

// List lists all WorkloadNetworkConfigurations in the indexer.
func (s *workloadNetworkConfigurationLister) List(selector labels.Selector) (ret []*v1alpha1.WorkloadNetworkConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WorkloadNetworkConfiguration))
	})
	return ret, err
}

// Get retrieves the WorkloadNetworkConfiguration from the index for a given name.
func (s *workloadNetworkConfigurationLister) Get(name string) (*v1alpha1.WorkloadNetworkConfiguration, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("workloadnetworkconfiguration"), name)
	}
	return obj.(*v1alpha1.WorkloadNetworkConfiguration), nil
}
